apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-portal-map
  namespace: ${NAMESPACE}
data:
  REACT_APP_API_URL: "${REACT_APP_API_URL}"
  DOMAIN_NAME: "${DOMAIN_NAME}"
  PUBLIC_URL: "/admin-portal"
  OAUTH_ENABLED: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-portal-svc
  namespace: ${NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: admin-portal
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-portal-deployment
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-portal
  template:
    metadata:
      labels:
        app: admin-portal
    spec:
      ${IMAGE_PULL_SECRET_BLOCK}
      containers:
        - name: admin-portal
          image: ${ADMIN_PORTAL_IMAGE}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: admin-portal-map
