env: local

namespace: baserock-backend

# Number of replicas when autoscaling is disabled
replicaCount: 1

# Service configuration
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [ ]
  host: "localhost"


config:
  TARGET_DB_NAME: "baserock-dev"
secrets:
  baserockBackend:
    ON_PREM_API_KEY:
    ON_PREM_URL: http://35.232.11.213:8000/v1/chat/completions
    ON_PREM_MODEL_NAME: Qwen/Qwen2.5-Coder-32B-Instruct
    ON_PREMISE_ADMIN_EMAIL: rishi@baserock.ai
    ON_PREMISE_USER_COUNT: "5"
    GITHUB_OAUTH_CLIENT_ID:
    GITHUB_OAUTH_CLIENT_SECRET:
    GITLAB_OAUTH_CLIENT_ID:
    GITLAB_OAUTH_CLIENT_SECRET:
    LINKEDIN_OAUTH_CLIENT_ID:
    LINKEDIN_OAUTH_CLIENT_SECRET:
    SONET_ANTHROPIC_API_KEY:
    SONET_VERTEX_AI_TOKEN:
    CHAT_GPT_AZURE_API_KEY:
    CHAT_GPT_AZURE_URL:
    TOKEN_PRIVATE_KEY:
    TOKEN_PUBLIC_KEY:
  dockercfg:
    data: { }