env: gcp
# Number of replicas when autoscaling is disabled
replicaCount: 1

# Service configuration
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  tls:
    - hosts:
        - app.dev.onprem.baserock.ai
      secretName: app-baserock-onprem-ssl-cert
  host: ""

config:
  TARGET_DB_NAME: "testdb"
secrets:
  baserockBackend:
    ON_PREM_API_KEY:
    ON_PREM_URL: http://35.232.11.213:8000/v1/chat/completions
    ON_PREM_MODEL_NAME: Qwen/Qwen2.5-Coder-32B-Instruct
    ON_PREMISE_ADMIN_EMAIL: rishi@baserock.ai
    ON_PREMISE_USER_COUNT: "5"
    CHAT_GPT_API_KEY:
    BASEROCK_EMAIL: rohit@baserock.ai
    BASEROCK_EMAIL_PASSWORD: cbawpdgtbxjydsvf
    GITHUB_OAUTH_CLIENT_ID:
    GITHUB_OAUTH_CLIENT_SECRET:
    GITLAB_OAUTH_CLIENT_ID:
    GITLAB_OAUTH_CLIENT_SECRET:
    LINKEDIN_OAUTH_CLIENT_ID:
    LINKEDIN_OAUTH_CLIENT_SECRET:
    SONET_ANTHROPIC_API_KEY:
    SONET_VERTEX_AI_TOKEN:
    CHAT_GPT_AZURE_API_KEY:
    CHAT_GPT_AZURE_URL:
    TOKEN_PRIVATE_KEY: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDStJlc2nGwKjbbn89waroVjOPztQ1ukuIyodfPY4BgREzQBLjFBw6xJNSqVV14F4022LOPnxf2iZE1fzKrp+ZYsSTEJZp1oJdpU94NsiM+qmrVlxSAQRU57et92yxp5mWH0GXuDlDH+GuHukm0Gos/Py/KHAPllkmRSYFQQdsHgEi/ZlNggD+Xor2Mf8seB/0KJ+AXb0ynAL/QUyIUTgTArym/EOn+G0VDFf4OOCAbz3PouDcpaL5WvRoYjf5fzMJNLcZ6dGyve4/1WWUFb9+Nf19XiyVMjP+egou43nH40eSDckDnz9KKB9diOLkELsyQphl2hOgJyhi+I8N90mD7AgMBAAECggEAawhYm2VPuQhIo5nzmwxsCIRwSx0efJvakZPK98t4q+4mAslTPqrOGMg3y2rftyBnmIPN+tf7KT5KaB18FNyOU2Fw5r6fTr9MCrISq2xhIPUanfNH87qb2Lh2FpGeZxElZC9Fh/73pA0aOnEz/Ww6bd9gHE/M3vRP3KC1Mpqxc4YXNuWHwLSR7goLPbCkI4Q3sQsWXQmYWob3ZD0/usGOCJV6YejPL0rN3S7KcyWD4JIKvp3CeqRb/qUoZ8Mtb8xZP8c10H46unC2OVIf0b1ZQKkyKb4pV4SSx7gHiKNt6zu9Sd+KzY0EXwbc2QE28wFiGJd2v9qc8ZboRY7TZ8DHOQKBgQD7oTU8Ay99ZoaPyMh9+OB+8Z6Gg0TkY4xBybfUBi74pAjBf2BXJ5ErEKvOYloEv7NpVtX5CDL6ozNDQy7wrofeunNkbOMldTiCSCmxVLnLxYjhYs7g8WlM9Ae5MpaH0fBC5Xn6xaaUS21iWniwPXcdjIpPRNeSejGvYVVV3u0DVwKBgQDWXW8yTsGZ2rVDtJlODSLqYZFj6bEJZNdv5+OI/U8r5nywxJsaYIhLResvU2ehZkK54Ebsj7CsO2xRWuo8mafNU2BQ4Ff47tRiiGdMP6O+s5LnOL+4FO66f+M7aGYVw1zwvXP5WbSmyV0GSn0339ZhY1eNU71uMob63Vz1U0IM/QKBgCMmkuwuOb0XzGZbkv5d/OZe1FlQDxike1xZVG+u6XLcX0jAhXHHWjUc4BM1lAOjz+lAMyXVqmFu2ONliDIg/2PywdneiCCcbmdssz5NaqL3ljZ9+g5cSuxwDoAle/e/MQP3UIHiiHGg08fwgXmFLJWZI10NbdvNbBFm1Gfpe0yDAoGAOajQLBv6/0NQ1nFReykVZy3vSYymTfyN5k/daA+aqBhLGdEIV0P35SddZ1Fr4oH7GLw215Ke1vT04b0unDZIaHYwxhBSGWdEQWynPF8x0C3FKeSdzQn0XL3hhS1DqD7wVODgvQVgDizDlNmcbNcMdw2dkyofHfEBVaENS/+lGJECgYBEqJLZgwaCqWoeuQfNmRkxfnALepiwlsrSU+B/e/RSygmFCIuh/lxeLY7a1zmFspAyc6t44K8danGf/nkV2kjQ6okQtwDScZ5D0696Qb1S1GHzUMRrnTv9sx/pDXz+dSrSyZ4kttOUzj7Is9f8q8vxpRNrpnAcm1yd3jSn6RHgCw==
    TOKEN_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0rSZXNpxsCo225/PcGq6FYzj87UNbpLiMqHXz2OAYERM0AS4xQcOsSTUqlVdeBeNNtizj58X9omRNX8yq6fmWLEkxCWadaCXaVPeDbIjPqpq1ZcUgEEVOe3rfdssaeZlh9Bl7g5Qx/hrh7pJtBqLPz8vyhwD5ZZJkUmBUEHbB4BIv2ZTYIA/l6K9jH/LHgf9CifgF29MpwC/0FMiFE4EwK8pvxDp/htFQxX+DjggG89z6Lg3KWi+Vr0aGI3+X8zCTS3GenRsr3uP9VllBW/fjX9fV4slTIz/noKLuN5x+NHkg3JA58/SigfXYji5BC7MkKYZdoToCcoYviPDfdJg+wIDAQAB
  dockercfg:
    data: { }
