---
apiVersion: v1
kind: Secret
metadata:
  name: learning-engine-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DB_NAME: "${MONGO_DB_NAME}"
  DB_URI: "${MONGO_URL}"
  DJANGO_SERVICE_BASE_URL: "${DJANGO_SERVICE_URL}"
  ENCRYPTION_PRIVATE_KEY: "${ENCRYPTION_PRIVATE_KEY}"
  GITHUB_APP_ID: "${GITHUB_APP_ID}"
  GITHUB_APP_ID_INT: "${GITHUB_APP_ID_INT}"
  GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
  GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
  GITHUB_PRIVATE_KEY: "${GITHUB_PRIVATE_KEY}"
  GITHUB_REDIRECT_URI: "${GITHUB_REDIRECT_URI}"
  POSTGRES_DB: "${POSTGRES_DB_NAME}"
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_USER: "${POSTGRES_USERNAME}"
  POSTGRES_PASSWORD: "${POSTGRES_DB_PASSWORD}"
  SERVICE_PORT: "80"
  VERIFY_VALUE: "${VALUE_VERIFICATION}"
  UPCASTED_COLLECTION: "${UPCASTED_COLLECTION}"
  REDIS_URL: "${REDIS_URL_LE}"
  CELERY_QUEUE: "${CELERY_QUEUE_NAME}"
  TOKEN_PUBLIC_KEY: "${TOKEN_PUBLIC_KEY}"
  JWT_PUBLIC_KEY: "${JWT_PUBLIC_KEY}"
---
# --- lerning-engine-service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-engine-service-deployment
  namespace: ${NAMESPACE}
  labels:
    app: learning-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learning-engine
  template:
    metadata:
      labels:
        app: learning-engine
    spec:
      ${IMAGE_PULL_SECRET_BLOCK}
      containers:
        - name: ${LE_SERVICE_DEPLOYMENT}
          image: ${LE_SERVICE_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: ${LE_GO_CPUS}
              memory: ${LE_GO_MEMORY}
            requests:
              cpu: ${LE_GO_CPUS}
              memory: ${LE_GO_MEMORY}
          envFrom:
            - secretRef:
                name: learning-engine-secret
---
# --- lerning-engine-service ---
apiVersion: v1
kind: Service
metadata:
  namespace: ${NAMESPACE}
  name: ${LE_SERVICE_DEPLOYMENT}-service
  labels:
    app: learning-engine
spec:
  selector:
    app: learning-engine
  ports:
    - name: service
      port: 80
      targetPort: 80
  type: ClusterIP
