---
# --- postgres-deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${POSTGRES_DEPLOYMENT}
  namespace: ${NAMESPACE}
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: ${POSTGRES_DB_NAME}
            - name: POSTGRES_USER
              value: ${POSTGRES_USERNAME}
            - name: POSTGRES_PASSWORD
              value: ${POSTGRES_DB_PASSWORD}
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: postgres-pv
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-pv
          emptyDir: {} # This creates an ephemeral storage

---
# --- postgres-service ---
apiVersion: v1
kind: Service
metadata:
  namespace: ${NAMESPACE}
  name: ${POSTGRES_SERVICE_DEPLOYMENT}
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: ${POSTGRES_PORT}
      targetPort: 5432
  type: ClusterIP
