# -- namespaces --#
export CERT_MANAGER_NAMESPACE="cert-manager-baserock"
export INGRESS_NAMESPACE="ingress-nginx"
export NAMESPACE="onpremise-baserock"

#--api keys--#
export LLM_API_KEY="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"
export LLM_MODEL_NAME="claude-3-5-sonnet-20241022"
export VOYAGE_API_KEY="pa-3jcfFMUy5JxSAdwqpLTiGE4lOb7vvzUIxbTRAUe0bYw"
export VOYAGE_MODEL_NAME="voyage-3"
#-- mongo --#
export UPCASTED_COLLECTION="testUpcastedSchemaSpec"
export MONGO_DB_PASSWORD="teste"
export MONGO_DB_NAME="microservice"
export MONGO_USERNAME="user"
export MONGO_DB_USER="root"
export MONGO_PORT="27017"
export MONGO_SERVICE="mongodb-service"
export MONGO_URL="mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@${MONGO_SERVICE}:${MONGO_PORT}/"

#-- postgres --#
export POSTGRES_DB_NAME="baserock-dev"
export POSTGRES_USERNAME="postgres"
export POSTGRES_DB_PASSWORD="postgres123"
export BACKEND_POSTGRES_ENABLED="true"
export BACKEND_POSTGRES_PERSISTENCE_SIZE="1Gi"

#-- redis --#
export BACKEND_REDIS_ENABLED="true"
export BACKEND_REDIS_ARCHITECTURE="standalone"
export BACKEND_REDIS_AUTH_ENABLED="false"
export BACKEND_REDIS_AUTH_PASSWORD=""
export BACKEND_REDIS_PERSISTENCE_SIZE="512Mi"

#--rabbitMQ --#
export MQ_HOST_NAME="rabbitmq-service"
export MQ_USERNAME="user"
export MQ_PASSWORD="password"
export RABBITMQ_PROTOCOL=""
export RABBITMQ_UI_NODEPORT=""
export RABBITMQ_AMQP_NODEPORT=""

#-- deployment names -- #
export CLIENT_DEPLOYMENT="client-deployment"
export UPCASTER_DEPLOYMENT="upcaster-deployment"
export FLINK_JOB_NAME="flink-aggregation-job"
export LE_SERVICE_DEPLOYMENT="learning-engine"
export MONGO_DEPLOYMENT="mongodb"
export POSTGRES_DEPLOYMENT="postgres-deployment"
export DJANGO_DEPLOYMENT="python-deployment"
export MQ_DEPLOYMENT="rabbitmq-deployment"
export MONGO_SERVICE="mongodb-service"
export DJANGO_SERVICE_DEPLOYMENT="python-service"
export POSTGRES_SERVICE_DEPLOYMENT="postgresql"
export RABBITMQ_SERVICE_DEPLOYMENT="rabbitmq-service"
export CELERY_WORKER_DEPLOYMENT="celery-worker"

#-- ingress & Cert--#
export CLIENT_BASE_URL="/it/catalog"
export LE_SERVICE_BASE_URL="/it/leService/(.*)"
export ISSUER_NAME="letsencrypt-production"
export CERT_SERVER="https://acme-v02.api.letsencrypt.org/directory"
export EMAIL="admin@baserock.ai"
export INGRESS_CLASS="nginx"
export HOST_PATH_TYPE="Prefix"
export INGRESS_PORT="80"
export CERT_MANAGER_VERSION="1.15.3"

#-- port & host --#
export LE_SERVICE_PORT="80"
export LE_DJANGO_PORT="80"
export CLIENT_PORT="80"
export MONGO_EXPRESS_PORT="8081"
export RABBITMQ_PORT="5672"
export RABBITMQ_UI_PORT="15672"
export RABBITMQ_HOST="http://${RABBITMQ_SERVICE_DEPLOYMENT}.${NAMESPACE}.svc.cluster.local:${RABBITMQ_PORT}"
export POSTGRES_PORT="5432"
export POSTGRES_HOST="${POSTGRES_SERVICE_DEPLOYMENT}.${NAMESPACE}.svc.cluster.local"
export DJANGO_SERVICE_URL="http://${DJANGO_SERVICE_DEPLOYMENT}.${NAMESPACE}.svc.cluster.local:${LE_DJANGO_PORT}"
export ENCRYPTION_PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----\nMIIEpQIBAAKCAQEAzja06ZwzkF9XA6T3AYIv0uRyfLteMp0rzk+NSFe15Uk0wyA1\ndWNFYPv6aQQLITtTpeaLhzT022BaKOQyPGWegaKlVoqsq1Z8EY8PR8euWKxB16o7\ndPG7+zy5pRtzulgsDURwKPXnOEIAnx5yw1Dxqk1/JPlfGFwizTna3Sj67s9mIFps\nKlIXyMkj5+iPDBQQMX692MacRo9tm7q1yzpDTZeRhIK1Gdf0MxoKqJJATyn8H/9E\nQnWjnRhbOwa/+V2rRzstgUVelLkIVTi7/t/c2VLdnkXGygZRyV5jy4pmRa9ciEGi\n2Iev71/6VQk+Mps8U10A2EV2Vy+WPqoH+IkmWwIDAQABAoIBAQDJak3ST6tdvIG1\nIY/RfWNQzam1gx1Cuplq7fDFVEZqKdLLM86DVe8SB4xSvoxQbS4KwOBPs73l+HqX\nriwTKf5kCIUNvm1g/Rw52k3GgpccLUQybiec1fASOQHq7qFexXhhjRMwLt8k5/LL\neGYHuCwTd5ZUeu4TUQr9ASFxGvHeBhw3+5mDSBW4HQ148SIn2+qUYGLRd0N2J/Np\nmhjDvsqIRlZz7PK5U4Q+CrgYjtl+450tse1z/+h5U+wKE1krfoK/iF9aKo5dWHdT\naZ/602Q+EqLGnpJxudRBgGsCzyMNGRD8cuOp4nlP5GvvelVp+VzGCR5qzEmGxGLz\n+99X5drBAoGBAO9UDKqw49X9DG6fYAfpkgZj57lmaIzEDuthziOFf+/9bPVPEmFJ\nKDy9RN+G8igpg9wEKRywQXGCFfeHyTjquH+AwE0DFkBdfp6xT5D1yyDGO+dSl5pW\n6EqvLh6l50AwV+ahBNGpWNkSOthzt9nDaVF9sSK3ehkYHHyvXbueXIvJAoGBANyU\nH3yIICPAsCj/Zo3JG8J8vsXsTeJH08x+f0lRlVjmW9qi0Ar4xBMVuhO28hIb91+5\nPA8Sbi7WUQ6m8OvDUQy/u5bZOznDUY7A+TtFR7yg7HBMuxQ2iRqOrQ+HNd2l49uf\nRH7H2Yvoj1pl4EIKIX5QO5lTST5LxMFyYVItEusDAoGAG/ReUmW9Bxa6qAU3q1Tt\n+I8c1vwORDr2XyoacO28BuU8H98vj2uDJq0Y6V8S0/wdacqWnsI7sq12MWaL63kH\nOeVpENXGeJgzHQgq+gyrwFVHU/rCuIVkNq0FnxDT1RyQd+Dg9jhop1pIw1Wo6Oe5\nWopq8VorCdlWIn49XZfeyXkCgYEAwqVTQ6k781DOIt99uBCHlpBOKInmEJAhrorR\n9/kuOUzOMZkKzSPIoq7BjTQbWS+kk6v5+7Lf2CT3Ul6uqt2oX/+xoeQAB3D8P2S6\nijsQmrvG6TJMxAF76xuMS++c8QK6l8trvhTNPFD0b2kHBD+8XqKedSaxs29ZKPuu\nNb3gu9ECgYEA34hoKBHTdADZcjCD5r3GccYtzPnR5kvocFZRw0OVxdgGHBIWccTY\nHzdnEm5IUYvjWEN4hvZWNsPBaOOp20qJRl0dTHsJ7zMAlp5eeERCSExzbwG53usb\nQ2nJYfIhzz0U5MKZ+7rysOFKfJasPXsdhpcxFAvvwy8yS2PFPIGzx/8=\n-----END RSA PRIVATE KEY-----\n"
export GITHUB_APP_ID="dev-on-prem-baserock-app"
export GITHUB_APP_ID_INT="1418828"
export GITHUB_CLIENT_ID="Iv23lidXqJ9uDItXGSfT"
export GITHUB_CLIENT_SECRET="835b4439096477ec61e917f464e15a37f895d2ae"
export GITHUB_PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAsgGqmIKgyfIA+eFnO0mnjDjflTkGPYLeRWOhFS8sqT/bBj9i\njx5JrVvRCb0Mnc5U95DO1ODNrsInkNJ+Vj3tFP7kOg/fMM1dUXLoQoHO7NhMMQoJ\nJcqQpS5hTVNRO9ABhfpPltt1cCcf8tgG2dYpdMvV0tvayA9upJTH0d41YtbNVlnO\nq2Bbh3IE/xG4OWz++9rLllIraa56Jy+uXYSkZZopIl4qwt5aTwUdAgn+ARdC2/MC\nhEOdljzi3hym6eSuamkmfML50YbEDOBXhsSB+eYF02vGYpREZAu+K9WoInxforp7\nqMFftPzO/quRQyZmSIvT8wgvUlKoeLMSre0YpQIDAQABAoIBAHvtARGwT7SIUPmm\nXTI/cvACYFYJHzkPtSLl261d7F/gXuGYm0s8MNsKQxvei7wJe8nm/Lfj0g5KiTUf\n9migMEAfvFBX4HCfaMpdjylOKftmEpVJgVjYD5+QDJnC2ZkklQrrWyGRo87yziFJ\nGGvr12zCxBhKi6Qgak0Wb47CfrRR4cfd9v6xZnzn0NIU4rfbNBVpBNh86mS5pIi8\n25e/X01QPxuDk91v3uNp/gx5Uq/r7TFLImOllz74k+zlIufREHYYdmB09HXXCHg0\ncHMXW7i/s8V7uh48VXK2tICNUoIeGzyF632eC/7g5a9GpZuQzzznlknMZFO7Q4gb\n5nCMXzkCgYEA2zAFKQevs9zkfDeXGkt8qOcT8qV2GmgY5zmORnvEFtHFx8effrSg\nkHysNGuaPgX6nh5eSlkDewRlIjMYtuPt680BQkxB2wk77jr0Pp/xwyrqXmpOxZwo\nT1rZLV8dVM+4DSSJ+z/KDpAD/hlGlx0Sj56Xk+eAB1u6w5NIwzQ5FX8CgYEAz+cQ\ndZWjaCCdR6NTC3ijnTB/0vOFQCljKLxFD5BbICxsp/CseVm1ZfmpwKLIrNdJ80vv\n7lICoqDV/ztXsoAwxlKekml4JiOsWY40oWearWRTAwGm/KgtQJMITyg2F49QyZuB\nVMtCYYL7apCOhqpSkwsvbTRaPH+Lf5Fm3MD0y9sCgYEAiJsEDE9TDSk1acmHrgav\n+eCSyR6gXdLU+n8fkgQe8Q3qUxmx6NkQXRymgsExT0iQqq1InNOfXLMfiNIJrCqg\nJN8O0tAOF0JJDK/He6RZnAaKLS/aSkSJxvNa+XEXKb2P+vjz2hgmiS7unhYIrbOb\n1tDDrZWRcISWAMAxkB9jGGcCgYBTg4gzE7ceXuuPGWaElyNyQ0c1oCkIyxdQB8De\nLajNVcsX8y/1VzntCstL3JgsBhdoqjppS3xPg7gy3M2voJr3L70PJ1riRzY2i09M\n/uc9e6106bcAizYSWH3f/lEsSZ+0PMlJHJU/wnPoLMV0BvtAoh+dCIivALUyu1/M\nkZ5EPQKBgA+CY6p9QiAi+VkNiByuuLMK8AvNaBadEGEYa3R2H0JIskIhDGL9gI4U\ngR1Ukbuyk/fqlVIQACIhEq49F5iYnmXjeq5eQ19o2cnV3o4gO7ez6u/JyULklD8a\ngMEVZvDPu7Gvg4X68JHB5EB5qWU44MeDeBQLajD/r66XxcBl2J5o\n-----END RSA PRIVATE KEY-----\n"
export GITHUB_REDIRECT_URI="https://${DOMAIN}${DOMAIN_PORT}/it/leService/github/app/callback"

#-- misc --#

export VALUE_VERIFICATION="false"
export USE_MINIKUBE="false"
export REDIS_URL="baserock-backend-redis-master.${NAMESPACE}.svc.cluster.local:6379"
export REDIS_URL_LE="redis://${REDIS_URL}/0"
export CELERY_QUEUE_NAME="celery_job_queue"
export LLM_PROVIDER="anthropic"

#-- backend-extras--#
export HELM_RELEASE="baserock-backend"
export IMAGE_PULL_POLICY="Always"
export INGRESS_PATH_TYPE="Prefix"
export SCHEME="https"
export EMAIL_ID="support@baserock.ai"
export USER_COUNT=1
export LICENSE_TYPE="TRIAL"
export BACKEND_PULL_POLICY="Always"
export BASEROCK_EMAIL_SMTP="onprem@baserock.ai"
export BASEROCK_EMAIL_PASSWORD_SMTP="ootejotartwhagaw"
export BACKEND_SERVICE_TYPE="ClusterIP"
export BACKEND_SERVICE_PORT="8080"
export BACKEND_SERVICE_TARGET_PORT="8080"
export BACKEND_REPLICA_COUNT="1"

#-- resource limits --#
export CLIENT_CPUS="0.5"
export UPCASTER_CPUS="0.5"
export FLINK_CPUS="0.5"
export FLINK_OPERATOR_CPU_REQUEST="10m"
export FLINK_OPERATOR_CPU_LIMIT="100m"
export LE_GO_CPUS="0.5"
export MONGO_CPUS="0.5"
export POSTGRES_CPUS="1"
export DJANGO_CPUS="1"
export RABBITMQ_CPUS="0.5"
export BACKEND_CPUS="0.5"
export BACKEND_CPUS_REQUESTS="0.5"
export CERT_CPU_REQUEST="10m"
export CERT_CPU_LIMIT="50m"
export FLINK_OPERATOR_CPU_REQUEST="10m"
export FLINK_OPERATOR_CPU_LIMIT="100m"
export CPU_REQUEST="100m"
export CPU_LIMIT="200m"
export TODO_WEB_APP_CPUS="0.5"
export TODO_WEB_SERVICE_CPUS="0.5"
export REDIS_CPUS="100m"
export CELERY_WORKER_CPUS="1"

export CLIENT_MEMORY="1Gi"
export UPCASTER_MEMORY="1Gi"
export FLINK_MEMORY="2Gi"
export LE_GO_MEMORY="512Mi"
export MONGO_MEMORY="1Gi"
export POSTGRES_MEMORY="1Gi"
export DJANGO_MEMORY="1Gi"
export RABBITMQ_MEMORY="512Mi"
export BACKEND_MEMORY="500Mi"
export BACKEND_MEMORY_REQUESTS="500Mi"
export CERT_MEM_REQUEST="32Mi"
export CERT_MEM_LIMIT="64Mi"
export FLINK_OPERATOR_MEM_REQUEST="64Mi"
export FLINK_OPERATOR_MEM_LIMIT="128Mi"
export FLINK_OPERATOR_MEM_REQUEST="64Mi"
export FLINK_OPERATOR_MEM_LIMIT="128Mi"
export TODO_WEB_APP_MEMORY="2Gi"
export TODO_WEB_SERVICE_MEMORY="2Gi"
export REDIS_MEMORY="256Mi"
export CELERY_WORKER_MEMORY="512Mi"
export CELERY_WORKER_STORAGE="1Gi"

#-- django --#
export MODEL_NAME="claude-3-5-sonnet-20241022"
export CHROMA_HOST="http://34.118.233.130:8000"
export CHROMA_TOKEN=""
export DEFINITION_MODE_THRESHOLD="100"
export LLM_ENABLED="True"
export MAX_TEST_CASES="10"
export POSITIVE_TEST_RATIO="0.5"

#-- client --#
export REACT_APP_API_URL="https://${DOMAIN}${DOMAIN_PORT}"
export REACT_APP_REDIRECT_BASE_URL="${REACT_APP_API_URL}/admin-portal/"
#-- todo-web-app --#
export TODO_WEB_SERVICE_URL="https://${DOMAIN}${DOMAIN_PORT}/todo"
export TODO_WEB_APP_CONTEXT_PATH="/todo-ui"
export TODO_WEB_APP_SERVER_PORT="8080"

#-- todo-web-service --#
export TODO_WEB_SERVICE_CONTEXT_PATH="/todo"
export TODO_WEB_SERVICE_SERVER_PORT="8080"
export TODO_WEB_SERVICE_SERVICE_NAME="todo-web-service"
export TODO_WEB_SERVICE_ENABLE_EXTENSION="true"
export TODO_WEB_SERVICE_EXTENSION_MODE="capture"
export TODO_WEB_SERVICE_GO_SERVER_BASE_URL="https://${DOMAIN}${DOMAIN_PORT}/it/leService"
export TODO_WEB_SERVICE_PUBLISHER_MODE="RabbitMQ"
export MQ_HOST="${MQ_HOST_NAME}"
export MQ_PORT="${RABBITMQ_PORT}"
export MQ_QUEUE="learning_engine_test_queue"
export MQ_USER="${MQ_USERNAME}"
export MQ_PASSWORD="${MQ_PASSWORD}"
export SPRING_DATASOURCE_URL="jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/todo"
export SPRING_DATASOURCE_USERNAME="${POSTGRES_USERNAME}"
export SPRING_DATASOURCE_PASSWORD="${POSTGRES_DB_PASSWORD}"
export MODEL_API_URL=""
export MAX_WORKERS="5"


