# -- images --#


if [[ "$USE_LATEST_TAGS" == "true" ]]; then
  export CLIENT_IMAGE="${REPO_NAME}/client:latest"
  export UPCASTER_IMAGE="${REPO_NAME}/upcaster:latest"
  export FLINK_IMAGE="${REPO_NAME}/flinkjob-rabbitmq-aggregation:latest"
  export DJANGO_IMAGE="${REPO_NAME}/le-django-server:latest"
  export LE_SERVICE_IMAGE="${REPO_NAME}/learning-engine-service:latest"
  export ADMIN_PORTAL_IMAGE="${REPO_NAME}/admin-portal-ui:latest"
  export TODO_WEB_APP_IMAGE="${REPO_NAME}/todo-web-app:latest"
  export TODO_WEB_SERVICE_IMAGE="${REPO_NAME}/todo-web-service:0.0.1"
  export BACKEND_IMAGE="${REPO_NAME}/facade-service"
  export BACKEND_TAG="latest"
  export CELERY_WORKER_IMAGE="${REPO_NAME}/celery-worker:latest"
  
  export MONGODB_IMAGE="${REPO_NAME}/mongo:latest"
  export POSTGRES_IMAGE="${REPO_NAME}/postgresql:latest"
  export RABBITMQ_IMAGE="${REPO_NAME}/rabbitmq:latest"
  export REDIS_IMAGE="${REPO_NAME}/redis:latest"
  export MONGO_EXPRESS_IMAGE="${REPO_NAME}/mongo-express:latest"
  export CERT_MANAGER_CONTROLLER_IMAGE="${REPO_NAME}/cert-manager-controller"
  export CERT_MANAGER_WEBHOOK_IMAGE="${REPO_NAME}/cert-manager-webhook"
  export CERT_MANAGER_CAINJECTOR_IMAGE="${REPO_NAME}/cert-manager-cainjector"
  export CERT_MANAGER_ACMESOLVER_IMAGE="${REPO_NAME}/cert-manager-acmesolver"
  export CERT_MANAGER_STARTUPIPCHECK_IMAGE="${REPO_NAME}/cert-manager-startupapicheck"
  export CERT_MANAGER_VERSION="latest"

  export INGRESS_CONTROLLER_IMAGE="${REPO_NAME}/ingress-nginx-controller:latest"
  export INGRESS_CERTGEN_IMAGE="${REPO_NAME}/kube-webhook-certgen:latest"
  export FLINK_OPERATOR_IMAGE="${REPO_NAME}/flink-kubernetes-operator:latest"
else
  export CLIENT_IMAGE="${REPO_NAME}/client:0.104.1-release-08-20-2025.1"
  export UPCASTER_IMAGE="${REPO_NAME}/upcaster:0.386.3-release-08-21-2025.3"
  export FLINK_IMAGE="${REPO_NAME}/flinkjob-rabbitmq-aggregation:0.58.21-release-07-23-2025.0"
  export DJANGO_IMAGE="${REPO_NAME}/le-django-server:0.386.3-release-08-21-2025.4"
  export LE_SERVICE_IMAGE="${REPO_NAME}/baserock-backend/learning-engine-service:0.222.1-release-08-20-2025.1"
  export ADMIN_PORTAL_IMAGE="${REPO_NAME}/admin-portal-ui:0.15.1-SM-1610-disable-oauth-flag.3"
  export TODO_WEB_APP_IMAGE="${REPO_NAME}/todo-web-app:0.0.1"
  export TODO_WEB_SERVICE_IMAGE="${REPO_NAME}/todo-web-service:0.0.1"
  export BACKEND_IMAGE="${REPO_NAME}/sapient-backend/facade-service"
  export BACKEND_TAG="1.220.0"
  export CELERY_WORKER_IMAGE="${REPO_NAME}/celery-worker:0.386.3-release-08-21-2025.5"
  
  export MONGODB_IMAGE="${REPO_NAME}/mongo:latest"
  export POSTGRES_IMAGE="${REPO_NAME}/postgresql:latest"
  export RABBITMQ_IMAGE="${REPO_NAME}/rabbitmq:latest"
  export REDIS_IMAGE="${REPO_NAME}/redis:latest"
  export MONGO_EXPRESS_IMAGE="${REPO_NAME}/mongo-express:latest"
  export CERT_MANAGER_CONTROLLER_IMAGE="${REPO_NAME}/cert-manager-controller"
  export CERT_MANAGER_WEBHOOK_IMAGE="${REPO_NAME}/cert-manager-webhook"
  export CERT_MANAGER_CAINJECTOR_IMAGE="${REPO_NAME}/cert-manager-cainjector"
  export CERT_MANAGER_ACMESOLVER_IMAGE="${REPO_NAME}/cert-manager-acmesolver"
  export CERT_MANAGER_STARTUPIPCHECK_IMAGE="${REPO_NAME}/cert-manager-startupapicheck"
  export INGRESS_CONTROLLER_IMAGE="${REPO_NAME}/ingress-nginx/controller:latest"
  export INGRESS_CERTGEN_IMAGE="${REPO_NAME}/ingress-nginx/kube-webhook-certgen:latest"
  export CERT_MANAGER_VERSION="latest"
  export FLINK_OPERATOR_IMAGE_REPO="${REPO_NAME}/flink-kubernetes-operator:latest"
fi

#-- llm versions--#
export LLM_MODEL_NAME="claude-3-5-sonnet-20241022"
export VOYAGE_MODEL_NAME="voyage-3"
export LLM_MODEL_NAME_ANTHROPIC="claude-sonnet-4-20250514"
export LLM_MODEL_NAME_BEDROCK="us.anthropic.claude-sonnet-4-20250514-v1:0"
export LLM_MODEL_NAME_VERTEX="claude-sonnet-4@20250514"
export LLM_FALLBACK_PROVIDERS="bedrock,vertex,"
