apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "baserock-backend.fullname" . }}-deployment
  labels:
    app: {{ include "baserock-backend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "baserock-backend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "baserock-backend.name" . }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
    {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
    {{- end }}
    {{- end }}
      containers:
        - name: baserock-backend
          image: {{ .Values.image.repository}}:{{ .Values.image.tag}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          envFrom:
            - configMapRef:
                name: {{ include "baserock-backend.fullname" . }}
            - secretRef:
                name: {{ include "baserock-backend.fullname" . }}
