apiVersion: v1
kind: Service
metadata:
  name: {{ include "baserock-backend.fullname" . }}-svc
  namespace: baserock-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.targetPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ include "baserock-backend.name" . }}