name: Deploy with Latest Tags

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod
        - minikube
      cloud_provider:
        description: 'Cloud provider'
        required: true
        default: 'gcp'
        type: choice
        options:
        - gcp
        - aws
        - minikube

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: production-385606
        service_account_key: ${{ secrets.GCP_PROD_IMAGE_UPLOAD_SERVICE_ACCOUNT }}
        
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
        
    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'
        
    - name: Setup Docker
      uses: docker/setup-buildx-action@v3
      
    - name: Make scripts executable
      run: |
        chmod +x commons/get-latest-tags.sh
        chmod +x deploy.sh
        chmod +x script.sh
        
    - name: Update latest tags
      run: ./commons/get-latest-tags.sh
      
    - name: Deploy with predefined inputs
      run: |
        # Create input for deploy.sh
        # Inputs: 1 (gcp), 2 (dev), 2 (Service Redeploy), 2 (Cloud Based), 2 (No cert manager), 1 (LoadBalancer)
        printf "1\n2\n2\n2\n2\n1\n" | ./deploy.sh
      env:
        # Add any environment variables needed for deployment
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
        
    - name: Deploy status
      run: |
        echo "✅ Deployment completed successfully!"
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Cloud Provider: ${{ github.event.inputs.cloud_provider }}" 